// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  header: string;
  item: string;
  logoLink: string;
  menu: string;
  menuLink: string;
  menuLinkActive: string;
  svg: string;
}
export const cssExports: CssExports;
export default cssExports;
