// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  black: string;
  description: string;
  root: string;
  title: string;
  white: string;
}
export const cssExports: CssExports;
export default cssExports;
